

Packages
```{r}
install.packages("devtools")
library(devtools)
devtools::install_github("psyteachr/introdataviz")
library(introdataviz)
library(ggplot2)
devtools::install_github("kassambara/ggpubr")
library(ggpubr)
```

Step 1: Generate seprate list of CpGs for each DMR and meta-merge file 
```{r}
library(reshape2)
## Chr 5
DMR_CpGs_Chr5 <- modelA_DMR_CpGs[(modelA_DMR_CpGs$chr=="chr5"), c("probe")]
## Chr 7
DMR_CpGs_Chr7 <- modelA_DMR_CpGs[(modelA_DMR_CpGs$chr=="chr7"), c("probe")]
## Chr 10
DMR_CpGs_Chr10 <- modelA_DMR_CpGs[(modelA_DMR_CpGs$chr=="chr10"), c("probe")]
## Chr 14
DMR_CpGs_Chr14 <- modelA_DMR_CpGs[(modelA_DMR_CpGs$chr=="chr14"), c("probe")]


## Incident kidney
Casestatus_incidentonly <- metaIncidentKidneydisease[,c("Basename","transitioned")]
Casestatus_incidentonly$transitioned[Casestatus_incidentonly$transitioned==0] <- "Control"
Casestatus_incidentonly$transitioned[Casestatus_incidentonly$transitioned==1] <- "Case"
#All cases
Casestatus_all <- meta312[,c("Basename","transitioned")]
Casestatus_all$transitioned[Casestatus_all$transitioned==0] <- "Control"
Casestatus_all$transitioned[Casestatus_all$transitioned==1] <- "Case"
```

Step 2: Generate long columns for each DMR for each Model
```{r}
##Model A
##Chr5
modelA_DMR_Chr5_betas = adjusted_modelA_beta[rownames(adjusted_modelA_beta) %in% DMR_CpGs_Chr5,]
modelA_DMR_Chr5_betas<-as.data.frame(t(modelA_DMR_Chr5_betas))
modelA_DMR_Chr5_betas$Basename <-row.names(modelA_DMR_Chr5_betas)
modelA_DMR_Chr5_betas<- modelA_DMR_Chr5_betas %>% select(Basename, everything())
modelA_DMR_Chr5_betas<-left_join(modelA_DMR_Chr5_betas, Casestatus_incidentonly, by = "Basename")
modelA_DMR_Chr5_betas$cg19837938 <-modelA_DMR_Chr5_betas$cg19837938-median(modelA_DMR_Chr5_betas$cg19837938)
modelA_DMR_Chr5_betas$cg25336267 <-modelA_DMR_Chr5_betas$cg25336267-median(modelA_DMR_Chr5_betas$cg25336267)
modelA_DMR_Chr5_betas_long <- melt(modelA_DMR_Chr5_betas, id = c("Basename", "transitioned")) 

##Chr7
modelA_DMR_Chr7_betas = adjusted_modelA_beta[rownames(adjusted_modelA_beta) %in% DMR_CpGs_Chr7,]
modelA_DMR_Chr7_betas<-as.data.frame(t(modelA_DMR_Chr7_betas))
modelA_DMR_Chr7_betas$Basename <-row.names(modelA_DMR_Chr7_betas)
modelA_DMR_Chr7_betas<- modelA_DMR_Chr7_betas %>% select(Basename, everything())
modelA_DMR_Chr7_betas<-left_join(modelA_DMR_Chr7_betas, Casestatus_incidentonly, by = "Basename")
modelA_DMR_Chr7_betas$cg07648698 <-modelA_DMR_Chr7_betas$cg07648698-median(modelA_DMR_Chr7_betas$cg07648698)
modelA_DMR_Chr7_betas$cg05349279 <-modelA_DMR_Chr7_betas$cg05349279-median(modelA_DMR_Chr7_betas$cg05349279)
modelA_DMR_Chr7_betas_long <- melt(modelA_DMR_Chr7_betas, id = c("Basename", "transitioned"))

##Chr10
modelA_DMR_Chr10_betas = adjusted_modelA_beta[rownames(adjusted_modelA_beta) %in% DMR_CpGs_Chr10,]
modelA_DMR_Chr10_betas<-as.data.frame(t(modelA_DMR_Chr10_betas))
modelA_DMR_Chr10_betas$Basename <-row.names(modelA_DMR_Chr10_betas)
modelA_DMR_Chr10_betas<- modelA_DMR_Chr10_betas %>% select(Basename, everything())
modelA_DMR_Chr10_betas<-left_join(modelA_DMR_Chr10_betas, Casestatus_incidentonly, by = "Basename")
modelA_DMR_Chr10_betas$cg23761815 <-modelA_DMR_Chr10_betas$cg23761815-median(modelA_DMR_Chr10_betas$cg23761815)
modelA_DMR_Chr10_betas$cg01132839 <-modelA_DMR_Chr10_betas$cg01132839-median(modelA_DMR_Chr10_betas$cg01132839)
modelA_DMR_Chr10_betas$cg13011182 <-modelA_DMR_Chr10_betas$cg13011182-median(modelA_DMR_Chr10_betas$cg13011182)
modelA_DMR_Chr10_betas_long <- melt(modelA_DMR_Chr10_betas, id = c("Basename", "transitioned"))

##Chr14
modelA_DMR_Chr14_betas = adjusted_modelA_beta[rownames(adjusted_modelA_beta) %in% DMR_CpGs_Chr14,]
modelA_DMR_Chr14_betas<-as.data.frame(t(modelA_DMR_Chr14_betas))
modelA_DMR_Chr14_betas$Basename <-row.names(modelA_DMR_Chr14_betas)
modelA_DMR_Chr14_betas<- modelA_DMR_Chr14_betas %>% select(Basename, everything())
modelA_DMR_Chr14_betas<-left_join(modelA_DMR_Chr14_betas, Casestatus_incidentonly, by = "Basename")
modelA_DMR_Chr14_betas$cg23672390 <-modelA_DMR_Chr14_betas$cg23672390-median(modelA_DMR_Chr14_betas$cg23672390)
modelA_DMR_Chr14_betas$cg06119833 <-modelA_DMR_Chr14_betas$cg06119833-median(modelA_DMR_Chr14_betas$cg06119833)
modelA_DMR_Chr14_betas_long <- melt(modelA_DMR_Chr14_betas, id = c("Basename", "transitioned"))



##Model B
##Chr5
modelB_DMR_Chr5_betas = adjusted_modelB_beta[rownames(adjusted_modelB_beta) %in% DMR_CpGs_Chr5,]
modelB_DMR_Chr5_betas<-as.data.frame(t(modelB_DMR_Chr5_betas))
modelB_DMR_Chr5_betas$Basename <-row.names(modelB_DMR_Chr5_betas)
modelB_DMR_Chr5_betas<- modelB_DMR_Chr5_betas %>% select(Basename, everything())
modelB_DMR_Chr5_betas<-left_join(modelB_DMR_Chr5_betas, Casestatus_all, by = "Basename")
modelB_DMR_Chr5_betas$cg19837938 <-modelB_DMR_Chr5_betas$cg19837938-median(modelB_DMR_Chr5_betas$cg19837938)
modelB_DMR_Chr5_betas$cg25336267 <-modelB_DMR_Chr5_betas$cg25336267-median(modelB_DMR_Chr5_betas$cg25336267)
modelB_DMR_Chr5_betas_long <- melt(modelB_DMR_Chr5_betas, id = c("Basename", "transitioned")) 

##Chr7
modelB_DMR_Chr7_betas = adjusted_modelB_beta[rownames(adjusted_modelB_beta) %in% DMR_CpGs_Chr7,]
modelB_DMR_Chr7_betas<-as.data.frame(t(modelB_DMR_Chr7_betas))
modelB_DMR_Chr7_betas$Basename <-row.names(modelB_DMR_Chr7_betas)
modelB_DMR_Chr7_betas<- modelB_DMR_Chr7_betas %>% select(Basename, everything())
modelB_DMR_Chr7_betas<-left_join(modelB_DMR_Chr7_betas, Casestatus_all, by = "Basename")
modelB_DMR_Chr7_betas$cg07648698 <-modelB_DMR_Chr7_betas$cg07648698-median(modelB_DMR_Chr7_betas$cg07648698)
modelB_DMR_Chr7_betas$cg05349279 <-modelB_DMR_Chr7_betas$cg05349279-median(modelB_DMR_Chr7_betas$cg05349279)
modelB_DMR_Chr7_betas_long <- melt(modelB_DMR_Chr7_betas, id = c("Basename", "transitioned"))

##Chr10
modelB_DMR_Chr10_betas = adjusted_modelB_beta[rownames(adjusted_modelB_beta) %in% DMR_CpGs_Chr10,]
modelB_DMR_Chr10_betas<-as.data.frame(t(modelB_DMR_Chr10_betas))
modelB_DMR_Chr10_betas$Basename <-row.names(modelB_DMR_Chr10_betas)
modelB_DMR_Chr10_betas<- modelB_DMR_Chr10_betas %>% select(Basename, everything())
modelB_DMR_Chr10_betas<-left_join(modelB_DMR_Chr10_betas, Casestatus_all, by = "Basename")
modelB_DMR_Chr10_betas$cg23761815 <-modelB_DMR_Chr10_betas$cg23761815-median(modelB_DMR_Chr10_betas$cg23761815)
modelB_DMR_Chr10_betas$cg01132839 <-modelB_DMR_Chr10_betas$cg01132839-median(modelB_DMR_Chr10_betas$cg01132839)
modelB_DMR_Chr10_betas$cg13011182 <-modelB_DMR_Chr10_betas$cg13011182-median(modelB_DMR_Chr10_betas$cg13011182)
modelB_DMR_Chr10_betas_long <- melt(modelB_DMR_Chr10_betas, id = c("Basename", "transitioned"))

##Chr14
modelB_DMR_Chr14_betas = adjusted_modelB_beta[rownames(adjusted_modelB_beta) %in% DMR_CpGs_Chr14,]
modelB_DMR_Chr14_betas<-as.data.frame(t(modelB_DMR_Chr14_betas))
modelB_DMR_Chr14_betas$Basename <-row.names(modelB_DMR_Chr14_betas)
modelB_DMR_Chr14_betas<- modelB_DMR_Chr14_betas %>% select(Basename, everything())
modelB_DMR_Chr14_betas<-left_join(modelB_DMR_Chr14_betas, Casestatus_all, by = "Basename")
modelB_DMR_Chr14_betas$cg23672390 <-modelB_DMR_Chr14_betas$cg23672390-median(modelB_DMR_Chr14_betas$cg23672390)
modelB_DMR_Chr14_betas$cg06119833 <-modelB_DMR_Chr14_betas$cg06119833-median(modelB_DMR_Chr14_betas$cg06119833)
modelB_DMR_Chr14_betas_long <- melt(modelB_DMR_Chr14_betas, id = c("Basename", "transitioned"))


```


Step 3: Make ggplots
```{r}


colours <- c("dodgerblue2", "darkorange")
theme<- theme(axis.title.y = element_text(size = 20),
               axis.text.y = element_text(size = 14),
              axis.title.x = element_text(size = 20),
              axis.text.x = element_text(size = 18),
              plot.title = element_text(hjust = 0.5, size=23),
              legend.title = element_blank(),
              legend.text = element_text(size = 18))
              
##Model A
png(filename = "DMR violin plots/Model A - Chr 5 - splitviolin.png", width=600, height=600)
ggplot(modelA_DMR_Chr5_betas_long, aes(x = variable, y = value, fill = transitioned)) + 
  geom_split_violin(alpha = .3) +
  geom_boxplot(width = .2, alpha = .6, show.legend = FALSE) +
  scale_fill_manual(values = colours) +
  theme +
  labs(x="CpG", y="∆β - median ∆β", title="Chr 5: 23,507,134 – 23,507,350")
dev.off()

png(filename = "DMR violin plots/Model A - Chr 7 - splitviolin.png", width=600, height=600)
ggplot(modelA_DMR_Chr7_betas_long, aes(x = variable, y = value, fill = transitioned)) + 
  geom_split_violin(alpha = .3) +
  geom_boxplot(width = .2, alpha = .6, show.legend = FALSE) +
  scale_fill_manual(values = colours)+
  theme +
  labs(x="CpG", y="∆β - median ∆β", title="Chr 7: 38,464,820 – 38,465,502")
dev.off()

png(filename = "DMR violin plots/Model A - Chr 10 - splitviolin.png", width=600, height=600)
ggplot(modelA_DMR_Chr10_betas_long, aes(x = variable, y = value, fill = transitioned)) + 
  geom_split_violin(alpha = .3) +
  geom_boxplot(width = .2, alpha = .6, show.legend = FALSE) +
  scale_fill_manual(values = colours) +
  theme +
  labs(x="CpG", y="∆β - median ∆β", title="Chr 10:  71,323,366 – 71,324,198")
dev.off()


png(filename = "DMR violin plots/Model A - Chr 14 - splitviolin.png", width=600, height=600)
ggplot(modelA_DMR_Chr14_betas_long, aes(x = variable, y = value, fill = transitioned)) + 
  geom_split_violin(alpha = .3) +
  geom_boxplot(width = .2, alpha = .6, show.legend = FALSE) +
  scale_fill_manual(values = colours) +
  theme +
  labs(x="CpG", y="∆β - median ∆β", title="Chr 14: 101,225,832 – 101,226,243")
dev.off()


#Model B

png(filename = "DMR violin plots/Model B - Chr 5 - splitviolin.png", width=600, height=600)
ggplot(modelB_DMR_Chr5_betas_long, aes(x = variable, y = value, fill = transitioned)) + 
  geom_split_violin(alpha = .3) +
  geom_boxplot(width = .2, alpha = .6, show.legend = FALSE) +
  scale_fill_manual(values = colours) +
  theme +
  labs(x="CpG", y="∆β - median ∆β", title="Chr 5: 23,507,134 – 23,507,350")
dev.off()

png(filename = "DMR violin plots/Model B - Chr 7 - splitviolin.png", width=600, height=600)
ggplot(modelB_DMR_Chr7_betas_long, aes(x = variable, y = value, fill = transitioned)) + 
  geom_split_violin(alpha = .3) +
  geom_boxplot(width = .2, alpha = .6, show.legend = FALSE) +
  scale_fill_manual(values = colours)+
  theme +
  labs(x="CpG", y="∆β - median ∆β", title="Chr 7: 38,464,820 – 38,465,502")
dev.off()

png(filename = "DMR violin plots/Model B - Chr 10 - splitviolin.png", width=600, height=600)
ggplot(modelB_DMR_Chr10_betas_long, aes(x = variable, y = value, fill = transitioned)) + 
  geom_split_violin(alpha = .3) +
  geom_boxplot(width = .2, alpha = .6, show.legend = FALSE) +
  scale_fill_manual(values = colours) +
  theme +
  labs(x="CpG", y="∆β - median ∆β", title="Chr 10:  71,323,366 – 71,324,198")
dev.off()


png(filename = "DMR violin plots/Model B - Chr 14 - splitviolin.png", width=600, height=600)
ggplot(modelB_DMR_Chr14_betas_long, aes(x = variable, y = value, fill = transitioned)) + 
  geom_split_violin(alpha = .3) +
  geom_boxplot(width = .2, alpha = .6, show.legend = FALSE) +
  scale_fill_manual(values = colours) +
  theme +
  labs(x="CpG", y="∆β - median ∆β", title="Chr 14: 101,225,832 – 101,226,243")
dev.off()


```

Grid-View 
```{r}
theme2<- theme(axis.title.y = element_text(size = 20),
               axis.text.y = element_text(size = 14),
              axis.title.x = element_text(size = 20),
              axis.text.x = element_text(size = 18),
              plot.title = element_text(hjust = 0.5, size=23),
              legend.title = element_blank(),
              legend.text = element_text(size = 18))


A1 <- ggplot(modelA_DMR_Chr5_betas_long, aes(x = variable, y = value, fill = transitioned)) + geom_split_violin(alpha = .3) +
  geom_boxplot(width = .2, alpha = .6, show.legend = FALSE) +
  scale_fill_manual(values = colours, name = "Case") +
  theme2+
  labs(x="CpG", y="∆β - median ∆β", title="Chr 5: 23,507,134 – 23,507,350")

A2 <- ggplot(modelA_DMR_Chr7_betas_long, 
             aes(x = variable, y = value, fill = transitioned)) + 
  geom_split_violin(alpha = .3) +
  geom_boxplot(width = .2, alpha = .6, show.legend = FALSE) +
  scale_fill_manual(values = colours, name = "Case")+
  theme2+
  labs(x="CpG", y="∆β - median ∆β", title="Chr 7: 38,464,820 – 38,465,502")

A3 <- ggplot(modelA_DMR_Chr10_betas_long, 
             aes(x = variable, y = value, fill = transitioned)) + 
  geom_split_violin(alpha = .3) +
  geom_boxplot(width = .2, alpha = .6, show.legend = FALSE) +
  scale_fill_manual(values = colours, name = "Case") +
  theme2+
  labs(x="CpG", y="∆β - median ∆β", title="Chr 10:  71,323,366 – 71,324,198")

A4 <- ggplot(modelA_DMR_Chr14_betas_long,
             aes(x = variable, y = value, fill = transitioned)) + 
  geom_split_violin(alpha = .3) +
  geom_boxplot(width = .2, alpha = .6, show.legend = FALSE) +
  scale_fill_manual(values = colours, name = "Case") +
  theme2+
    labs(x="CpG", y="∆β - median ∆β", title="Chr 14: 101,225,832 – 101,226,243")

#Model B

B1 <- ggplot(modelB_DMR_Chr5_betas_long, 
             aes(x = variable, y = value, fill = transitioned)) + 
  geom_split_violin(alpha = .3) +
  geom_boxplot(width = .2, alpha = .6, show.legend = FALSE) +
  scale_fill_manual(values = colours, name = "Case") +
  theme2+
    labs(x="CpG", y="∆β - median ∆β", title="Chr 5: 23,507,134 – 23,507,350")

B2 <- ggplot(modelB_DMR_Chr7_betas_long, 
             aes(x = variable, y = value, fill = transitioned)) + 
  geom_split_violin(alpha = .3) +
  geom_boxplot(width = .2, alpha = .6, show.legend = FALSE) +
  scale_fill_manual(values = colours, name = "Case")+
  theme2+
   labs(x="CpG", y="∆β - median ∆β", title="Chr 7: 38,464,820 – 38,465,502")

B3 <- ggplot(modelB_DMR_Chr10_betas_long, 
             aes(x = variable, y = value, fill = transitioned)) + 
  geom_split_violin(alpha = .3) +
  geom_boxplot(width = .2, alpha = .6, show.legend = FALSE) +
  scale_fill_manual(values = colours, name = "Case") +
  theme2+
    labs(x="CpG", y="∆β - median ∆β", title="Chr 10:  71,323,366 – 71,324,198")

B4 <- ggplot(modelB_DMR_Chr14_betas_long, 
             aes(x = variable, y = value, fill = transitioned)) + 
  geom_split_violin(alpha = .3) +
  geom_boxplot(width = .2, alpha = .6, show.legend = FALSE) +
  scale_fill_manual(values = colours, name = "Case") +
  theme2+
    labs(x="CpG", y="∆β - median ∆β", title="Chr 14: 101,225,832 – 101,226,243")


ggarrange(
  A1, A2, A3, A4, B1, B2, B3, B4,  ncol = 4, nrow = 2, 
  common.legend = TRUE, legend = "bottom"
  )

```

