---
title: "Adjusting beta values"
output: html_notebook
---
Step 1: Load functions .
```{r}
library(data.table)
library(future.apply)
library(lmerTest)
library(xlsx)
library(ENmix)
library(dplyr)
library(tidyverse)
library(EpiDISH)
library(reshape2)
library(ggplot2) 
```

Step 2: Function for calculating residuals.
```{r}
get_residuals = function(cpg,meta,rhs_formula)
{
  meta$cpg = cpg
  me_model=lmer(as.formula(paste("cpg ~ ", rhs_formula,sep="")),meta)
  res_vector = residuals(me_model) + fixef(me_model)[1]
  return(res_vector)
}
# 2. Wrapping function to provide adjusted beta values
get_adjusted_beta = function(beta, meta, fixed_effects, random_effects)
{
  ####### Compile the RHS of the formula from fixed and random effects ###############
  t1=Sys.time()
  rhs_formula = paste(paste(fixed_effects,collapse = " + "),paste("(",paste("1",random_effects,sep = "|",collapse = ") + ("),")",sep=""),sep = " + ")
  print("planning...")
  plan("future::multisession")
  print("fitting...")
  tts=future_apply(beta, MARGIN = 1, FUN = get_residuals, meta = meta, rhs_formula=rhs_formula)
  print("transposing...")
  tts=t(tts)
  print("transposed")
  colnames(tts) = colnames(beta)
  t2=Sys.time()
  print(t1)
  print(t2)
  return(tts)
}
```

Step 3: Adjust betas for model 1 and 2  
```{r}

fixed_effects=c("PC1","PC2","PC3","PC3","Smoke","Sex","Age")
random_effects= c("Id", "Sentrix_ID","Sentrix_Position", "Year")
trait_name="transitioned" 

## Model A
adjusted_modelA_beta = get_adjusted_beta(beta=betaIncidentKidneydisease, meta = metaIncidentKidneydisease,fixed_effects = fixed_effects,random_effects = random_effects)

## Model B
adjusted_modelB_beta = get_adjusted_beta(beta=beta312, meta = meta312,fixed_effects = fixed_effects,random_effects = random_effects)

# Save as data frames
adjusted_modelA_beta<- as.data.frame(adjusted_modelA_beta)
adjusted_modelB_beta<- as.data.frame(adjusted_modelB_beta)


## Write files
fwrite(adjusted_modelA_beta,"Power calculation files/adjusted_modelA_beta.csv",col.names = TRUE, row.names = TRUE)
fwrite(adjusted_modelB_beta,"Power calculation files/adjusted_modelB_beta.csv",col.names = TRUE, row.names = TRUE)


```

Step 4: SDs 
```{r}
# Model 1
adjusted_modelA_sd = as.data.frame(apply(adjusted_modelA_beta, MARGIN = 1, sd)) # per CpG standard deviation in group 1
adjusted_modelA_control_sd = as.data.frame(apply(adjusted_modelA_beta[,metaIncidentKidneydisease$transitioned==0], MARGIN = 1, sd)) # controls per CpG standard deviation in group 1
adjusted_modelA_case_sd = as.data.frame(apply(adjusted_modelA_beta[,metaIncidentKidneydisease$transitioned==1], MARGIN = 1, sd)) # transitioneds per CpG standard deviation in group 1
grouping1=as.character(metaIncidentKidneydisease$transitioned)

## Model 2
adjusted_modelB_sd = as.data.frame(apply(adjusted_modelB_beta, MARGIN = 1, sd)) # per CpG standard deviation in group 1
adjusted_modelB_control_sd = as.data.frame(apply(adjusted_modelB_beta[,meta312$transitioned==0], MARGIN = 1, sd)) # controls per CpG standard deviation in group 1
adjusted_modelB_case_sd = as.data.frame(apply(adjusted_modelB_beta[,meta312$transitioned ==1], MARGIN = 1, sd)) # transitioneds per CpG standard deviation in group 1
grouping2=as.character(meta312$transitioned)



## Save adjusted models
save(adjusted_modelA_control_sd,adjusted_modelA_case_sd,grouping1, file = "Power calculation files/adjusted_modelA_sd.RData")
save(adjusted_modelB_control_sd,adjusted_modelB_case_sd,grouping2, file = "Power calculation files/adjusted_modelB_sd.RData")



```

Step 5: Means 
```{r}
## Model 1
adjusted_modelA_mean = as.data.frame(apply(adjusted_modelA_beta, MARGIN = 1, mean)) # per CpG standard deviation in group 1
adjusted_modelA_control_mean = as.data.frame(apply(adjusted_modelA_beta[,metaIncidentKidneydisease$transitioned==0], MARGIN = 1, mean)) # controls per CpG standard deviation in group 1
adjusted_modelA_case_mean = as.data.frame(apply(adjusted_modelA_beta[,metaIncidentKidneydisease$transitioned==1], MARGIN = 1, mean)) # cases per CpG standard deviation in group 1
grouping1=as.character(metaIncidentKidneydisease$transitioned)

## Model 2
adjusted_modelB_mean = as.data.frame(apply(adjusted_modelB_beta, MARGIN = 1, mean)) # per CpG standard deviation in group 1
adjusted_modelB_control_mean = as.data.frame(apply(adjusted_modelB_beta[,meta312$transitioned==0], MARGIN = 1, mean)) # controls per CpG standard deviation in group 1
adjusted_modelB_case_mean = as.data.frame(apply(adjusted_modelB_beta[,meta312$transitioned==1], MARGIN = 1, mean)) # cases per CpG standard deviation in group 1
grouping2=as.character(meta312$transitioned)

## Save adjusted models
save(adjusted_modelA_control_mean,adjusted_modelA_case_mean,grouping1, file = "Power calculation files/adjusted_modelA_mean.RData")
save(adjusted_modelB_control_mean,adjusted_modelB_case_mean,grouping2, file = "Power calculation files/adjusted_modelB_mean.RData")

```
